"""Small governance catalog for the teaching checker.

This file is pure data: each dictionary describes one index.
It uses realistic JNE table and column names, but the entries are dummy samples.
Replace this catalog from JNE_Index_List_Relational.xlsx before production use.
"""

CATALOG: list[dict] = [
    {
        "index_code": "COMP1B1",
        "element": "Completeness",
        "rule_family": "completeness",
        "table": "CMS_CNOTE",
        "params": {"column": "CNOTE_NO", "cnote_column": "CNOTE_NO"},
        "description": "CMS_CNOTE.CNOTE_NO must not be null or empty",
    },
    {
        "index_code": "COMP1D2",
        "element": "Completeness",
        "rule_family": "completeness",
        "table": "CMS_DRCNOTE",
        "params": {"column": "DRCNOTE_CNOTE_NO", "cnote_column": "DRCNOTE_CNOTE_NO"},
        "description": "CMS_DRCNOTE.DRCNOTE_CNOTE_NO must not be null or empty",
    },
    {
        "index_code": "VALD1B6",
        "element": "Validity",
        "rule_family": "validity_regex",
        "table": "CMS_CNOTE",
        "params": {"column": "CNOTE_SERVICES_CODE", "pattern": r"^[A-Z0-9]{2,5}$", "cnote_column": "CNOTE_NO"},
        "description": "CMS_CNOTE.CNOTE_SERVICES_CODE must look like a service code",
    },
    {
        "index_code": "VALD1B12",
        "element": "Validity",
        "rule_family": "validity_regex",
        "table": "CMS_CNOTE",
        "params": {"column": "CNOTE_ORIGIN", "pattern": r"^[A-Z]{3}$", "cnote_column": "CNOTE_NO"},
        "description": "CMS_CNOTE.CNOTE_ORIGIN must be a three-letter branch code",
    },
    {
        "index_code": "UNIQ1B1",
        "element": "Uniqueness",
        "rule_family": "uniqueness",
        "table": "CMS_CNOTE",
        "params": {"columns": ["CNOTE_NO"], "cnote_column": "CNOTE_NO"},
        "description": "CMS_CNOTE.CNOTE_NO must be unique",
    },
    {
        "index_code": "UNIQ1D1",
        "element": "Uniqueness",
        "rule_family": "uniqueness",
        "table": "CMS_DRCNOTE",
        "params": {"columns": ["DRCNOTE_NO"], "cnote_column": "DRCNOTE_CNOTE_NO"},
        "description": "CMS_DRCNOTE.DRCNOTE_NO must be unique",
    },
    {
        "index_code": "CONS1B15",
        "element": "Consistency",
        "rule_family": "pair_consistency",
        "table": "CMS_CNOTE",
        "params": {
            "left_table": "CMS_APICUST",
            "left_column": "APICUST_WEIGHT",
            "right_table": "CMS_CNOTE",
            "right_column": "CNOTE_WEIGHT",
            "join_key": "CNOTE_NO",
            "left_join_key": "APICUST_CNOTE_NO",
            "right_join_key": "CNOTE_NO",
            "cnote_column": "CNOTE_NO",
        },
        "description": "API customer weight should match CNOTE weight when both are present",
    },
    {
        "index_code": "CONS1B12",
        "element": "Consistency",
        "rule_family": "pair_consistency",
        "table": "CMS_CNOTE",
        "params": {
            "left_table": "CMS_APICUST",
            "left_column": "APICUST_ORIGIN",
            "right_table": "CMS_CNOTE",
            "right_column": "CNOTE_ORIGIN",
            "join_key": "CNOTE_NO",
            "left_join_key": "APICUST_CNOTE_NO",
            "right_join_key": "CNOTE_NO",
            "cnote_column": "CNOTE_NO",
        },
        "description": "API customer origin should match CNOTE origin when both are present",
    },
    {
        "index_code": "TIME1B99",
        "element": "Timeliness",
        "rule_family": "timeliness",
        "table": "CMS_CNOTE",
        "params": {
            "start_table": "CMS_CNOTE",
            "start_column": "CNOTE_CRDATE",
            "end_table": "CMS_MHI_HOC",
            "end_column": "MHI_APPROVE_DATE",
            "join_key": "CNOTE_NO",
            "start_join_key": "CNOTE_NO",
            "end_join_key": "MHI_CNOTE_NO",
            "cnote_column": "CNOTE_NO",
        },
        "description": "CNOTE creation should happen before HOC approval",
    },
    {
        "index_code": "TIME1P3",
        "element": "Timeliness",
        "rule_family": "timeliness",
        "table": "CMS_DRSHEET",
        "params": {
            "start_table": "CMS_DRSHEET",
            "start_column": "DRSHEET_DATE",
            "end_table": "CMS_CNOTE_POD",
            "end_column": "CNOTE_POD_DATE",
            "join_key": "CNOTE_NO",
            "start_join_key": "DRSHEET_CNOTE_NO",
            "end_join_key": "CNOTE_POD_NO",
            "cnote_column": "DRSHEET_CNOTE_NO",
        },
        "description": "Runsheet date should happen before POD date",
    },
    {
        "index_code": "INTG1D1",
        "element": "Integrity",
        "rule_family": "integrity_orphan",
        "table": "CMS_DRCNOTE",
        "params": {
            "child_table": "CMS_DRCNOTE",
            "child_column": "DRCNOTE_CNOTE_NO",
            "parent_table": "CMS_CNOTE",
            "parent_column": "CNOTE_NO",
            "cnote_column": "DRCNOTE_CNOTE_NO",
        },
        "description": "Every DRCNOTE CNOTE reference should exist in CMS_CNOTE",
    },
    {
        "index_code": "INTG1I1",
        "element": "Integrity",
        "rule_family": "integrity_orphan",
        "table": "CMS_MFCNOTE",
        "params": {
            "child_table": "CMS_MFCNOTE",
            "child_column": "MFCNOTE_MAN_NO",
            "parent_table": "CMS_MANIFEST",
            "parent_column": "MANIFEST_NO",
            "cnote_column": "MFCNOTE_NO",
        },
        "description": "Every MFCNOTE manifest reference should exist in CMS_MANIFEST",
    },
]
